name: Lint and Tests

on: [push, pull_request]

jobs:
  lint-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8.18

    - name: Install dependencies
      run: |
        pip install python-dateutil
        pip install fastapi
        pip install pytest
        pip install isort
        pip install black
        pip install httpx
        pip install joblib
        pip install scikit-learn==1.0.1

    - name: Check isort
      run: |
        isort --check .
       
    - name: Check black
      run: |
        black --check .

    - name: Run pytest
      run: |
        pytest
